### ISSUE TITLE
FilledInput does not have a label property

### ISSUE THREAD

**Issue by itsderek23** [uxpin-merge/material-ui-merge#29]
The "Label" property does not appear for the FilledInput component.

https://material.io/components/text-fields#filled-text-field

![image](https://user-images.githubusercontent.com/7880/93796922-c68fde80-fbf8-11ea-9fc4-40019fac1aeb.png)

**Comment by swmoore84** [comment]
FilledInput itself does not have a label property, a label can be added when using a TextField which is built on top of FilledInput.
The solution for this is to use the TextField component and change the variant to filled.
See documentation regarding TextField [https://material-ui.com/components/text-fields/](https://material-ui.com/components/text-fields/)
