### ISSUE TITLE
"TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string ..." running `uxpin-merge push` on Windows

### ISSUE THREAD

**Issue by itsderek23** [uxpin-merge/material-ui-merge#42]
A user has reported that `uxpin-merge push` fails with this repo on Windows. He's having no issues w/uxpin boilerplate. 

Error screenshot:

![image](https://user-images.githubusercontent.com/7880/97337842-60752780-1846-11eb-98ce-3d8ef99e1d16.png)

Node Version: v12.16.1

`uxpin-merge` works fine for me on OSX w/Node v12.18.1.

**Comment by jakubsgit** [comment]
The "Windows subsystem for Linux" has not installed. After that installation everything went through as needed. Problem can be mark as solved.

**Comment by itsderek23** [comment]
Great @jacekzlowocki and thanks @matthewchigira for the hand!

https://www.uxpin.com/docs/merge/working-on-windows/
